---
- name: Copy register.json
  become: true
  become_user: root
  template: 
    src: register.json.j2
    dest: /tmp/register.json
    owner: root 
    group: root 
    mode: 0644

- name: Copy aops_agent.conf
  become: true
  become_user: root
  template:
    src: agent.conf.j2
    dest: /etc/aops/agent.conf
    owner: root
    group: root
    mode: 0644

